[soonsal]
title = "순살브리핑 ─ 날짜별"
url = "https://soonsal.com/newsletters"
entrySelector = "ul.li_body.holder li.tit"
titleSelector = "a.list_text_title._fade_link span"
linkSelector = "a.list_text_title._fade_link"
waitUntil = "networkidle"

[booding]
title = "부딩"
url = "https://www.booding.co/blog"
entrySelector = "div.gallery-item-container"
titleSelector = "h2 div.blog-post-homepage-title-color.blog-post-homepage-title-font"
linkSelector = "a._2oveR._2llBS._1e-gz._3T8tF.has-custom-focus"
contentSelector = "div._81XUh"
imageSelector = "div[class^='gallery-item-content']"
waitUntil = "networkidle"
