[soonsal]
title = "순살브리핑 ─ 날짜별"
url = "https://soonsal.com/newsletters"
entrySelector = "ul.li_body.holder li.tit"
titleSelector = "a.list_text_title._fade_link span"
linkSelector = "a.list_text_title._fade_link"
waitUntil = "networkidle"

[booding]
title = "부딩"
url = "https://www.booding.co/blog"
entrySelector = "div.gallery-item-container.visible.hover-animation-fade-in"
titleSelector = "h2 div.blog-post-homepage-title-color.blog-post-homepage-title-font._3gVhF"
linkSelector = "a._2oveR._2llBS._1e-gz._3T8tF.has-custom-focus._2U5_L"
contentSelector = "div._81XUh"
imageSelector = "div[class^='gallery-item-content']"
waitUntil = "networkidle"

[themiilk_investing_latest]
title = "더밀크 ─ Investing ─ 최신기사"
url = "https://themiilk.com/investing/latest"
entrySelector = "div.content-wrapper ul.list li.item"
titleSelector = "h2.title.label-middle-title.bold.ellipsis.two"
linkSelector = "div.image-wrapper.remove-line-height a"
contentSelector = "p.description.label-middle-description.ellipsis.three"
imageSelector = "div.image-wrapper.remove-line-height a div.image-box"
waitUntil = "networkidle"

[themiilk_investing_rising-stocks]
title = "더밀크 ─ Investing ─ 유망주"
url = "https://themiilk.com/investing/category/rising-stocks"
entrySelector = "div.content-wrapper ul.list li.item"
titleSelector = "h2.title.label-middle-title.bold.ellipsis.two"
linkSelector = "div.image-wrapper.remove-line-height a"
contentSelector = "p.description.label-middle-description.ellipsis.three"
imageSelector = "div.image-wrapper.remove-line-height a div.image-box"
waitUntil = "networkidle"

[themiilk_investing_stock-basics]
title = "더밀크 ─ Investing ─ 미국주식 101"
url = "https://themiilk.com/investing/category/stock-basics"
entrySelector = "div.content-wrapper ul.list li.item"
titleSelector = "h2.title.label-middle-title.bold.ellipsis.two"
linkSelector = "div.image-wrapper.remove-line-height a"
contentSelector = "p.description.label-middle-description.ellipsis.three"
imageSelector = "div.image-wrapper.remove-line-height a div.image-box"
waitUntil = "networkidle"

[themiilk_conferences]
title = "더밀크 ─ Conference"
url = "https://themiilk.com/conferences"
entrySelector = "div.content-wrapper ul.list li.item"
titleSelector = "h2.title.label-middle-title.bold.ellipsis.two"
linkSelector = "div.image-wrapper.remove-line-height a"
contentSelector = "p.description.label-middle-description.ellipsis.three"
imageSelector = "div.image-wrapper.remove-line-height a div.image-box"
waitUntil = "networkidle"