[soonsal]
title = "순살브리핑 ─ 날짜별"
url = "https://soonsal.com/newsletters"
entrySelector = "ul.li_body.holder li.tit"
titleSelector = "a.list_text_title._fade_link span"
linkSelector = "a.list_text_title._fade_link"
waitUntil = "networkidle"

[booding]
title = "부딩"
url = "https://www.booding.co/blog"
entrySelector = "div.gallery-item-container"
titleSelector = "h2 div.blog-post-homepage-title-color.blog-post-homepage-title-font"
linkSelector = "a._2oveR._2llBS._1e-gz._3T8tF.has-custom-focus"
contentSelector = "div._81XUh"
imageSelector = "div[class^='gallery-item-content']"
waitForSelector = "div.gallery-item-container"

[mk_premium_msg]
title = "매경프리미엄 ─ 기획연재 ─ 매경이 전하는 세상의 지식"
url = "https://www.mk.co.kr/premium/series/20007/"
entrySelector = "div.content_left div.list_area2 dl.article_list"
titleSelector = "dt.tit a"
linkSelector = "dt.tit a"
contentSelector = "span.subtxt"
imageSelector = "img.img_bd"
waitUntil = "networkidle"
